CREATE TABLE VEICULO(
ID INT NOT NULL PRIMARY KEY,
TIPOCOMBUSTIVEL VARCHAR NOT NULL,
ULTIMAMARCACAOHODOMETRO INT NOT NULL,
KMPERCORRIDO INT,
KMPORLITRO INT
)

CREATE TABLE ABASTECIMENTO(
IDABASTECIMENTO INT IDENTITY(100,1) PRIMARY KEY,
DATA VARCHAR NOT NULL,
IDVEICULO INT NOT NULL,
QTDLITROS DOUBLE NOT NULL,
CUSTOABASTECIMENTO DOUBLE NOT NULL,
MARCACAOHODOMETRO INT NOT NULL,
FOREIGN KEY(IDVEICULO) REFERENCES VEICULO(ID)
)
